### ISSUE TITLE
License for Repository

### ISSUE THREAD

**Issue by sidkshatriya** [franciscolopezsancho/akka-topics#1]
Thanks for putting up these akka examples on GitHub and linking to this repo from https://www.manning.com/books/akka-in-action-second-edition. The presence of a Github repository for a book is always a great plus!

The first edition of the "Akka in Action" book repository https://github.com/RayRoestenburg/akka-in-action has a LICENSE file and it would be awesome if you can also add a license to this repo too.

**Comment by franciscolopezsancho** [comment]
Hi @sidkshatriya. Very good point, thanks!

P.S. sorry for the late reply
